### ISSUE TITLE
Error in creating conda environment

### ISSUE THREAD

**Issue by hansonlee2017** [FBoyles/3dsig#1]
In the readme.md

`conda env build -f fergalicious.yml `

should be 

`conda env create -f fergalicious.yml`

**Comment by FBoyles** [comment]
> In the readme.md
> 
> `conda env build -f fergalicious.yml`
> 
> should be
> 
> `conda env create -f fergalicious.yml`

Yep - turns out I can't type. Thanks for pointing this out - closing as I've corrected the mistake.
